# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=26.1.2.0
group=xyz.faewulf.piggyback
java_version=25

# Common
minecraft_version=26.1.2
minecraft_version_max=26.2
mod_name=Piggyback
mod_author=Faewulf
mod_id=piggyback
license=CC-BY-NC-SA-4.0
credits=
description=Allow player riding each other and replace the default player sitting mechanic with a piggyback-style ride. Carry your friends on your back for fun, teamwork, or pure chaos!
minecraft_version_range=[1.21.11, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
mdg_version=2.0.141

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.145.4+26.1.2
fabric_loader_version=0.18.6
loom_version=1.15.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.7-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx8G -Xms1G -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Lib
modmenu_version=18.0.0
faewulfs_lib_version=1.4.0
#publish
# default
# confirm for real publish
confirm_publish=false
modrinth_id=yP77bAiA
curseforge_id=1241247
# release, beta, alpha
version_type=release