# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.1.1
group=xyz.faewulf.piggyback
java_version=21
# Common
minecraft_version=1.21.10
minecraft_version_max=1.22
mod_name=Piggyback
mod_author=Faewulf
mod_id=piggyback
license=CC-BY-NC-SA-4.0
credits=
description=Allow player riding each other and replace the default player sitting mechanic with a piggyback-style ride. Carry your friends on your back for fun, teamwork, or pure chaos!
minecraft_version_range=[1.21.10, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.10-20251010.172816
mdg_version=2.0.115
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12
# Fabric
fabric_version=0.136.0+1.21.10
fabric_loader_version=0.17.3
loom_version=1.11-SNAPSHOT
modmenu_version=16.0.0-rc.1
# Forge
forge_version=60.0.5
forge_loader_version_range=[60,)
forge_gradle_version=[6.0.24,6.2)
# NeoForge
neoforge_version=21.10.29-beta
neoforge_loader_version_range=[6,)
# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
# Lib
faewulfs_lib_version=1.3.2
#publish
# default
# confirm for real publish
confirm_publish=false
modrinth_id=yP77bAiA
curseforge_id=1241247
# release, beta, alpha
version_type=release